before_script:
  - npm install --silent

test-node:
  image: node:10
  stage: test
  script:
    - npm run coverage
  artifacts:
    name: "sscrypto_coverage_${CI_BUILD_ID}_${CI_BUILD_REF}"
    when: always
    expire_in: 6 mos
    paths:
    - coverage/

test-browser:
  image: nexus-docker.tardis.seald.io/seald/docker-browser-testing:CHROME_76
  stage: test
  script:
    - npm run test-browser

.deploy:
  image: node:10
  stage: deploy
  script:
    - npm run build
    - npm publish
  only:
    - tags
